#!/usr/bin/with-contenv bash

#    Copyright 2021 Robby Zapmino
#
#    This file is part of golang-unified-push-rewrite-proxy-docker.
#
#    golang-unified-push-rewrite-proxy-docker is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.

if [ ! -z ${FCM_KEY+x} ]; then
   args="${args}--fcm=${FCM_KEY} "
fi

if [ ! -z ${GOTIFY_ADDRESS+x} ]; then
   args="${args}--gotify=${GOTIFY_ADDRESS} "
fi

if [ -z ${LISTEN_ADDRESS+x} ]; then
    LISTEN_ADDRESS="127.0.0.1"
fi

if [ -z ${LISTEN_PORT+x} ]; then
    LISTEN_PORT="5000"
fi

exec \
        s6-setuidgid abc \
        /usr/bin/up_rewrite \
        ${args} \
        -l${LISTEN_ADDRESS}:${LISTEN_PORT}
